# Generated by Django 5.0.9 on 2024-12-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='URL',
            new_name='url',
        ),
    ]
