# Generated by Django 5.0.9 on 2024-12-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_image_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user_likes',
            new_name='users_like',
        ),
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
